name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Execute remote SSH commands on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 54.89.171.134
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            NODE_BIN="/home/ubuntu/.nvm/versions/node/v20.20.0/bin"

            # Verify correct Node & npm
            $NODE_BIN/node -v
            $NODE_BIN/npm -v

            # Go to project
            cd ~/ci-cd
            git pull origin main

            # Install & build
            $NODE_BIN/npm install
            $NODE_BIN/npm run build

            
